-- ============================================================
-- Fix: Payment recording fails with "Unable to record the payment"
-- Run this in the Supabase SQL Editor (Dashboard → SQL Editor → New query)
-- ============================================================

-- Step 1: Ensure the order_payment_history table exists
-- (it is defined in apply_fixes.sql but may have been missed)
create table if not exists public.order_payment_history (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  payment_amount numeric(10, 2) not null check (payment_amount > 0),
  previous_paid_amount numeric(10, 2) not null default 0,
  new_paid_amount numeric(10, 2) not null default 0,
  previous_status text not null default 'Pending',
  new_status text not null default 'Pending',
  remaining_balance numeric(10, 2) not null default 0,
  recorded_by uuid references public.users(id) on delete set null,
  note text,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists order_payment_history_order_idx
  on public.order_payment_history (order_id, created_at desc);

create index if not exists order_payment_history_created_at_idx
  on public.order_payment_history (created_at desc);

alter table public.order_payment_history enable row level security;

drop policy if exists "order_payment_history_select_admin" on public.order_payment_history;
create policy "order_payment_history_select_admin"
  on public.order_payment_history
  for select
  to authenticated
  using (
    public.is_admin()
  );

-- Step 2: Drop ALL overloaded versions of record_order_payment
-- (covers the old 2-arg, old 4-arg, and current 3-arg signatures)
drop function if exists public.record_order_payment(bigint, numeric);
drop function if exists public.record_order_payment(bigint, numeric, text);
drop function if exists public.record_order_payment(bigint, numeric, text, uuid);

-- Step 3: Recreate the clean, correct 3-parameter version
create or replace function public.record_order_payment(
  target_order_id bigint,
  payment_amount numeric,
  payment_note text default null
)
returns table (
  id bigint,
  client_id uuid,
  customer_name text,
  phone text,
  location text,
  product_id uuid,
  product_name text,
  quantity_kg numeric,
  price_per_kg numeric,
  total_price numeric,
  paid_amount numeric,
  remaining_balance numeric,
  is_credit boolean,
  status text,
  previous_status text,
  payment_amount_recorded numeric,
  became_completed boolean,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  selected_order public.orders%rowtype;
  current_user_id uuid := auth.uid();
  previous_paid_amount_value numeric(10, 2);
  new_paid_amount numeric(10, 2);
  actual_payment_recorded_value numeric(10, 2);
  new_status text;
  remaining_balance_value numeric(10, 2);
  previous_status_value text;
begin
  if current_user_id is null then
    raise exception 'Not authenticated.';
  end if;

  if not public.is_admin() then
    raise exception 'Only admins can record payments.';
  end if;

  if payment_amount is null or payment_amount <= 0 then
    raise exception 'Payment amount must be greater than zero.';
  end if;

  select *
  into selected_order
  from public.orders
  where orders.id = target_order_id
  for update;

  if not found then
    raise exception 'Selected order was not found.';
  end if;

  if selected_order.status = 'Cancelled' then
    raise exception 'Cancelled orders cannot receive payments.';
  end if;

  if selected_order.status = 'Completed' then
    raise exception 'This order is already completed and cannot receive additional payments.';
  end if;

  if selected_order.paid_amount >= selected_order.total_price then
    raise exception 'This order is already fully paid.';
  end if;

  previous_status_value := selected_order.status;
  previous_paid_amount_value := selected_order.paid_amount;
  new_paid_amount := least(
    selected_order.total_price,
    previous_paid_amount_value + payment_amount
  );
  actual_payment_recorded_value := new_paid_amount - previous_paid_amount_value;
  remaining_balance_value := greatest(selected_order.total_price - new_paid_amount, 0);
  new_status := case
    when remaining_balance_value = 0 then 'Completed'
    when selected_order.status = 'Pending' then 'Received'
    else selected_order.status
  end;

  update public.orders as o
  set
    paid_amount = new_paid_amount,
    is_credit = new_paid_amount < o.total_price,
    status = new_status
  where o.id = selected_order.id
  returning * into selected_order;

  insert into public.order_payment_history (
    order_id,
    payment_amount,
    previous_paid_amount,
    new_paid_amount,
    previous_status,
    new_status,
    remaining_balance,
    recorded_by,
    note
  )
  values (
    selected_order.id,
    actual_payment_recorded_value,
    previous_paid_amount_value,
    selected_order.paid_amount,
    previous_status_value,
    selected_order.status,
    remaining_balance_value,
    current_user_id,
    nullif(trim(coalesce(payment_note, '')), '')
  );

  return query
  select
    selected_order.id,
    selected_order.client_id,
    selected_order.customer_name,
    selected_order.phone,
    selected_order.location,
    selected_order.product_id,
    selected_order.product_name,
    selected_order.quantity_kg,
    selected_order.price_per_kg,
    selected_order.total_price,
    selected_order.paid_amount,
    remaining_balance_value,
    selected_order.is_credit,
    selected_order.status,
    previous_status_value,
    actual_payment_recorded_value,
    selected_order.status = 'Completed' and previous_status_value <> 'Completed',
    selected_order.created_at;
end;
$$;

-- Step 4: Set correct permissions
revoke execute on function public.record_order_payment(bigint, numeric, text) from anon;
grant execute on function public.record_order_payment(bigint, numeric, text)
  to authenticated;
